# Generated by Django 6.0 on 2026-01-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='e_tin',
            field=models.CharField(blank=True, help_text='Electronic Tax Identification Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='trade_license_number',
            field=models.CharField(blank=True, help_text='Trade License Number', max_length=100, null=True),
        ),
    ]
