# Generated by Django 6.0 on 2026-01-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_e_tin_customuser_trade_license_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='business_email',
            field=models.EmailField(blank=True, help_text='Business contact email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nid_number',
            field=models.CharField(blank=True, help_text='National ID Number', max_length=50, null=True),
        ),
    ]
