# Generated by Django 6.0 on 2026-01-23 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_business_email_customuser_nid_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='business_phone_number',
            field=models.CharField(blank=True, help_text='Business contact phone number', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +999999999. Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
