# Generated by Django 6.0 on 2026-01-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_business_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification_count',
            field=models.IntegerField(default=0, help_text='Number of verification attempts'),
        ),
    ]
