# Generated by Django 6.0 on 2025-12-29 14:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=255)),
                ('store_description', models.TextField()),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to='store_logos/')),
                ('store_banner', models.ImageField(blank=True, null=True, upload_to='store_banners/')),
                ('store_email', models.EmailField(max_length=254)),
                ('store_phone', models.CharField(max_length=20)),
                ('store_website', models.URLField(blank=True, null=True)),
                ('store_address', models.CharField(max_length=255)),
                ('store_city', models.CharField(max_length=100)),
                ('store_state', models.CharField(max_length=100)),
                ('store_country', models.CharField(max_length=100)),
                ('store_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(limit_choices_to={'user_type': 'company'}, on_delete=django.db.models.deletion.CASCADE, related_name='store_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='part_categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='parts.partcategory')),
            ],
            options={
                'verbose_name_plural': 'Part Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('part_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('refurbished', 'Refurbished'), ('used', 'Used')], max_length=20)),
                ('brand', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_in_stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_sold', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('out_of_stock', 'Out of Stock'), ('discontinued', 'Discontinued'), ('pending', 'Pending Review')], db_index=True, default='pending', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('warranty_months', models.IntegerField(blank=True, null=True)),
                ('warranty_description', models.TextField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=8, null=True)),
                ('dimensions', models.CharField(blank=True, help_text='L x W x H in cm', max_length=100, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('reviews_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_for_sale', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='parts.partcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartCompatibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('car_make', models.CharField(db_index=True, max_length=100)),
                ('car_model', models.CharField(db_index=True, max_length=100)),
                ('car_year_from', models.IntegerField()),
                ('car_year_to', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='parts.carpart')),
            ],
            options={
                'ordering': ['car_make', 'car_model'],
            },
        ),
        migrations.CreateModel(
            name='PartImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='parts/%Y/%m/%d/')),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='parts.carpart')),
            ],
            options={
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='carpart',
            index=models.Index(fields=['seller', 'status'], name='parts_carpa_seller__5854f7_idx'),
        ),
        migrations.AddIndex(
            model_name='carpart',
            index=models.Index(fields=['category'], name='parts_carpa_categor_ddf69c_idx'),
        ),
        migrations.AddIndex(
            model_name='carpart',
            index=models.Index(fields=['brand'], name='parts_carpa_brand_9b1b1c_idx'),
        ),
        migrations.AddIndex(
            model_name='carpart',
            index=models.Index(fields=['price'], name='parts_carpa_price_0c6401_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partcompatibility',
            unique_together={('part', 'car_make', 'car_model', 'car_year_from', 'car_year_to')},
        ),
    ]
