# Generated by Django 6.0 on 2025-12-29 14:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('make', models.CharField(db_index=True, max_length=100)),
                ('model', models.CharField(db_index=True, max_length=100)),
                ('year', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)])),
                ('mileage', models.IntegerField(help_text='Mileage in kilometers', validators=[django.core.validators.MinValueValidator(0)])),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('cvt', 'CVT')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric'), ('lpg', 'LPG')], max_length=20)),
                ('engine_capacity', models.DecimalField(blank=True, decimal_places=2, help_text='Engine capacity in liters', max_digits=4, null=True)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state_province', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('archived', 'Archived'), ('pending', 'Pending Review')], db_index=True, default='pending', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('body_type', models.CharField(blank=True, max_length=50, null=True)),
                ('doors', models.IntegerField(blank=True, null=True)),
                ('seats', models.IntegerField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=list, help_text="List of features: ['AC', 'Power Steering', 'ABS', etc.]")),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_for_sale', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='cars/%Y/%m/%d/')),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
            options={
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CarSpecification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('horsepower', models.IntegerField(blank=True, null=True)),
                ('torque', models.IntegerField(blank=True, null=True)),
                ('acceleration_0_100', models.DecimalField(blank=True, decimal_places=2, help_text='0-100 km/h in seconds', max_digits=4, null=True)),
                ('top_speed', models.IntegerField(blank=True, help_text='km/h', null=True)),
                ('fuel_consumption_city', models.DecimalField(blank=True, decimal_places=2, help_text='km/l in city', max_digits=5, null=True)),
                ('fuel_consumption_highway', models.DecimalField(blank=True, decimal_places=2, help_text='km/l on highway', max_digits=5, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, help_text='mm', max_digits=5, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, help_text='mm', max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='mm', max_digits=5, null=True)),
                ('weight', models.IntegerField(blank=True, help_text='kg', null=True)),
                ('warranty_remaining', models.CharField(blank=True, max_length=100, null=True)),
                ('service_history', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='cars.car')),
            ],
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['seller', 'status'], name='cars_car_seller__4cf064_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['make', 'model', 'year'], name='cars_car_make_0aabde_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['price'], name='cars_car_price_f6b08b_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['city'], name='cars_car_city_60a4a5_idx'),
        ),
    ]
