# Generated by Django 6.0 on 2026-01-23 09:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parts', '0002_partreview_partreviewhelpfulness_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Shop/Location name', max_length=255)),
                ('location_type', models.CharField(choices=[('shop', 'Shop'), ('service', 'Service Center'), ('warehouse', 'Warehouse')], default='shop', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=8, help_text='Latitude coordinate', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, help_text='Longitude coordinate', max_digits=11)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(default='Bangladesh', max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('operating_hours', models.CharField(help_text='e.g., "9 AM - 9 PM" or "24/7"', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Shop photo', null=True, upload_to='shop_locations/%Y/%m/')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes for approval/rejection', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_locations', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(limit_choices_to={'is_seller': True}, on_delete=django.db.models.deletion.CASCADE, related_name='shop_locations', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, help_text='Associated company store (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='parts.companystore')),
            ],
            options={
                'verbose_name': 'Shop Location',
                'verbose_name_plural': 'Shop Locations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seller', 'approval_status'], name='locations_s_seller__c6232d_idx'), models.Index(fields=['latitude', 'longitude'], name='locations_s_latitud_f33c01_idx'), models.Index(fields=['city', 'approval_status'], name='locations_s_city_1871a2_idx')],
            },
        ),
    ]
