# Generated by Django 6.0 on 2025-12-29 14:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_new_message', models.BooleanField(default=True)),
                ('email_listing_update', models.BooleanField(default=True)),
                ('email_expert_response', models.BooleanField(default=True)),
                ('email_review_received', models.BooleanField(default=True)),
                ('email_seller_response', models.BooleanField(default=True)),
                ('email_forum_reply', models.BooleanField(default=True)),
                ('email_part_available', models.BooleanField(default=True)),
                ('email_price_alert', models.BooleanField(default=True)),
                ('email_verification_status', models.BooleanField(default=True)),
                ('email_account_alert', models.BooleanField(default=True)),
                ('email_system_announcement', models.BooleanField(default=False)),
                ('app_new_message', models.BooleanField(default=True)),
                ('app_listing_update', models.BooleanField(default=True)),
                ('app_expert_response', models.BooleanField(default=True)),
                ('app_review_received', models.BooleanField(default=True)),
                ('app_seller_response', models.BooleanField(default=True)),
                ('app_forum_reply', models.BooleanField(default=True)),
                ('app_part_available', models.BooleanField(default=True)),
                ('app_price_alert', models.BooleanField(default=True)),
                ('app_verification_status', models.BooleanField(default=True)),
                ('app_account_alert', models.BooleanField(default=True)),
                ('app_system_announcement', models.BooleanField(default=True)),
                ('email_frequency', models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], default='instant', max_length=20)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('new_message', 'New Message'), ('listing_update', 'Listing Update'), ('expert_response', 'Expert Response'), ('review_received', 'Review Received'), ('seller_response', 'Seller Response'), ('forum_reply', 'Forum Reply'), ('part_available', 'Part Available'), ('price_alert', 'Price Alert'), ('verification_status', 'Verification Status'), ('account_alert', 'Account Alert'), ('system_announcement', 'System Announcement')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_f77590_idx')],
            },
        ),
    ]
